
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DEC END EQ FOR INC ITER NUMBER START VARstatement : FORstatement : FOR ITERstatement : FOR DEC ITERstatement : FOR START NUMBER END NUMBERstatement : DEC ITER FORstatement : INC ITER FORstatement : FOR NUMBER NUMBERstatement : FOR INC ITERstatement : FOR VAR EQ NUMBER NUMBER'
    
_lr_action_items = {'FOR':([0,11,12,],[2,18,19,]),'DEC':([0,2,],[3,6,]),'INC':([0,2,],[4,9,]),'$end':([1,2,5,13,15,16,18,19,22,23,],[0,-1,-2,-3,-7,-8,-5,-6,-4,-9,]),'ITER':([2,3,4,6,9,],[5,11,12,13,16,]),'START':([2,],[7,]),'NUMBER':([2,7,8,17,20,21,],[8,14,15,21,22,23,]),'VAR':([2,],[10,]),'EQ':([10,],[17,]),'END':([14,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> FOR','statement',1,'p_statement_rule1','for.py',63),
  ('statement -> FOR ITER','statement',2,'p_statement_rule2','for.py',67),
  ('statement -> FOR DEC ITER','statement',3,'p_statement_rule3','for.py',71),
  ('statement -> FOR START NUMBER END NUMBER','statement',5,'p_statement_rule4','for.py',75),
  ('statement -> DEC ITER FOR','statement',3,'p_statement_rule5','for.py',84),
  ('statement -> INC ITER FOR','statement',3,'p_statement_rule6','for.py',87),
  ('statement -> FOR NUMBER NUMBER','statement',3,'p_statement_rule7','for.py',90),
  ('statement -> FOR INC ITER','statement',3,'p_statement_rule8','for.py',97),
  ('statement -> FOR VAR EQ NUMBER NUMBER','statement',5,'p_statement_rule9','for.py',101),
]
